// action constants for 'state' data
export const STATES_FETCH_ERROR = "STATES_FETCH_ERROR"; 
export const STATES_FETCH_INITIATED = "STATES_FETCH_INITIATED";
export const STATES_FETCH_COMPLETED = "STATES_FETCH_COMPLETED";
