#!/usr/bin/python

import requests

header_data = {
    'Cookie': 'HoldTheDoor=',
    'User-Agent': 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)',
    'Referer': 'http://173.246.108.142/level2.php'
}

form_data = {
    'id': '41',
    'type': 'text',
    'holdthedoor': 'submit',
    'key': ''
}

for i in range(1024):
    r = requests.post("http://173.246.108.142/level2.php", data=form_data, headers=header_data)
    print (i, r.status_code, r.reason)

print "done!"
